"""Add freelancer_id to client table

Revision ID: a8e5d76da1a0
Revises: 
Create Date: 2025-03-12 17:44:10.277966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e5d76da1a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('freelancer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_client_freelancer_id', 'freelancer', ['freelancer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('freelancer_id')

    # ### end Alembic commands ###
